avatartravel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('blogs.urls', namespace='blogs')),
]

blogs/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

blogs/models.py
from django.db import models

# Create your models here.

blogs/views.py
from django.shortcuts import render


def index(request):
    """docstring for index"""
    return render(request, 'blogs/index.html')

blogs/templates/blogs/index.html
{% load staticfiles %}
<form action="{% url 'blogs:index' %}" method="post">
{% csrf_token %}
<h1>アバター旅行記</h1>

<div style="float: left;">
    <h2>1. アバターの選択</h2>
    <table>
        <tr>
            <td><img src="{% static 'blogs/images/avatar_eri.jpg' %}" /><br />
                <label><input type="radio" name="avatarId" value="eri" checked="checked" /><span>えり</span></label></td>
            <td><img src="{% static 'blogs/images/avatar_soun.jpg' %}" /><br />
                <label><input type="radio" name="avatarId" value="soun" /><span>早雲</span></label></td>
            <td><img src="{% static 'blogs/images/avatar_o2.jpg' %}" /><br />
                <label><input type="radio" name="avatarId" value="o2" /><span>Ｏ２</span></label></td>
        </tr>
    </table>
</div>
<div style="float: left;">
<h2>2. 行き先の選択</h2>
<p>行き先 <select name="destination">
    <option value="Prague">プラハ</option>
    <option value="London">ロンドン</option>
    <option value="Roma">ローマ</option>
    <option value="New York">ニューヨーク</option>
    <option value="Las Vegas">ラスベガス</option>
    <option value="San Francisco">サンフランシスコ</option>
    <option value="Giza">ギザ</option>
    <option value="Dubai">ドバイ</option>
</select></p>

<h2>3. 出発</h2>
<p>アバターと行き先を選択したら、このボタン→<input type="submit" value="出発" />をクリックしてください</p>

<h2>最近の旅行記</h2>
<ul>
    <li>えり in Paris (出発日：2015/3/3)</li>
    <li>早雲 in Giza (出発日：2015/3/2)</li>
    <li>Ｏ２ in Dubai (出発日：2015/2/28)</li>
</ul>
</div>
</form>